/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:53e54d44-ad06-4465-b2ac-ef3e4ca61dbe",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yLRkWiT8b",
    "aws_user_pools_web_client_id": "6aip56rjtf73nbh5g8gr254t0k",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://zk7pmbkz5ngqrjvjmku3wy3xsm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-uw5e2khrpzdzlkdrgapq52xtta",
    "aws_user_files_s3_bucket": "amplifyappa455ae52f99f4a6e97f81f42138752c205717-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
